### PR TITLE
Update simple_contact.php

### PR DESCRIPTION
**Pull request by samuelstein**
function mergePluginConfig should be protected to work with grav 0.9.28

### CODE REVIEW

**Comment by namaless** [comment]
Sorry for delay, but why need protected? It's a internal method and not extended from the plugin class. Do not wrong with the plugin class method https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Plugin.php#L147

**Comment by samuelstein** [comment]
if you won't change the access modifier, the plugin is not working and you get an error in the log.

**Comment by namaless** [comment]
Check the plugin version, because on the gpm use 1.0.2, but here is 1.0.4.

I have asked some days ago the update the repository url but no one changed on gpm.

If you want to fix you can download the zip here and update manualy, all working fine after.

**Comment by Sommerregen** [comment]
Hi @namaless ,

I'm just stopping by. The problem why GPM doesn't see you current version 1.0.4 is that you changed your tag names from "v1.0.2" to "1.0.3" and "1.0.4". GPM can't handle this. Thus, just update your tags to be in a consistent format (either all with "v" in front or not) and GPM will see it :-)

**Comment by namaless** [comment]
@Sommerregen deprecated because i not use my time to improve, but anyone can extend or replace this. I use for my old projects the other plugin with form api, more fine than this, but it's only for who want.

Btw i release another release with old tag format. Please confirm if working or not.

**Comment by Sommerregen** [comment]
@namaless Good to know! Concerning GPM. Currently Grav sees version "1.0.4" but not "1.0.5", but as far as I can see, both are identical and it doesn't matter if you abandoned the project. Otherwise you maybe have to change the release tags for "1.0.3" and "1.0.4", too. Thus, that all releases are consistent.

Sorry, to can't help you any further. GPM acts really weird in such cases!

**Pull request closed without merging**
